services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodered:
    image: nodered/node-red:latest
    dns: "8.8.8.8"
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Zurich
    depends_on:
      - postgres
    volumes:
      - nodered_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    environment:
      - PORT=80
      - POSTGRES_URL
    depends_on:
      - postgres
    env_file: ".env"

  test_postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5434:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  test_postgres_data:
  nodered_data: